apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  template:
    spec:
      containers:
        - name: argocd-server
          volumeMounts:
            - name: styles
              mountPath: /shared/app/custom
      volumes:
        - name: styles
          configMap:
            name: argocd-styles-cm
