---
apiVersion: v1
kind: Service
metadata:
  name: database
spec:
  clusterIP: None # Headless service for StatefulSet identity
  selector:
    app: immich-postgres
  ports:
    - protocol: TCP
      port: 5432
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: immich-postgres
spec:
  serviceName: database
  replicas: 1
  selector:
    matchLabels:
      app: immich-postgres
  template:
    metadata:
      labels:
        app: immich-postgres
    spec:
      initContainers:
        - name: fix-permissions
          image: busybox:latest
          command:
            - sh
            - -c
            - |
              if [ -z "$(ls /var/lib/postgresql/data)" ]; then
                echo "Data directory is empty, setting permissions..."
                chmod 755 /var/lib/postgresql/data
              else
                echo "Data directory not empty, fixing ownership..."
                chown -R 999:999 /var/lib/postgresql/data
              fi
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
      containers:
        - name: postgres
          image: ghcr.io/immich-app/postgres:14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
          env:
            - name: POSTGRES_INITDB_ARGS
              value: "--data-checksums"
          envFrom:
            - secretRef:
                name: immich-postgres
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
            - name: dshm
              mountPath: /dev/shm
          # Updated Healthchecks using the internal script
          readinessProbe:
            exec:
              command: ["/usr/local/bin/healthcheck.sh"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["/usr/local/bin/healthcheck.sh"]
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: dshm
          emptyDir:
            medium: Memory
            sizeLimit: 128Mi
  volumeClaimTemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: postgres-data
      spec:
        storageClassName: local-path
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
