{{- $root := $ }}
{{- $email := tpl .Values.issuer.email $root | quote }}
{{- if and .Values.issuer.enabled $email }}
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-cloudflare
spec:
  acme:
    email: {{ tpl .Values.issuer.email $ | quote }}
    privateKeySecretRef:
      name: letsencrypt-cloudflare-private-key
    server: {{ .Values.issuer.server }}
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-cloudflare-api
              key: CLOUDFLARE_API_TOKEN
{{- end }}
