{{- $domain := .Values.global.metadata.domain -}}
{{- $certificate := .Values.certificate -}}
{{- if and $certificate.enabled $domain -}}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-certificate
spec:
  dnsNames:
    - {{ printf "%s" $domain | quote }}
    - {{ printf "*.%s" $domain | quote }}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-cloudflare
  usages:
    - digital signature
    - key encipherment
  secretName: wildcard-tls
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
{{- end }}
