apiVersion: k3d.io/v1alpha5
kind: Simple

metadata:
  name: local

servers: 1
agents: 3

ports:
  - port: 80:80
    nodeFilters:
      - loadbalancer
  - port: 443:443
    nodeFilters:
      - loadbalancer

volumes:
  - volume: "$PWD/k8s/data/storage:/var/lib/rancher/k3s/storage"
    nodeFilters:
      - all

registries:
  create:
    name: registry.localhost
    host: 0.0.0.0
    hostPort: "5000"
    volumes:
      - "$PWD/k8s/data/registry:/var/lib/registry"

options:
  k3s:
    extraArgs:
      - arg: --disable=traefik
        nodeFilters:
          - server:*
      - arg: "--tls-san=*.localhost"
        nodeFilters:
          - server:*
