apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: installer
spec:
  description: A basic AppProject for ArgoCD
  sourceRepos:
    - "*"
  destinations:
    - server: {{ .Values.cluster.server }}
      namespace: "*"
