apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-styles-cm
data:
  theme.css: |
    .theme-light {
      --banner-background-color: #DAD5C1;
      --banner-color: #504B31;
    }

    .theme-dark {
      --banner-background-color: #504B31;
      --banner-color: #DAD5C1;
    }
