apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

namespace: argocd

resources:
  - argocd-styles-cm.yaml

patches:
  - path: patches/argocd-cm.yaml
  - path: patches/argocd-rbac-cm.yaml
  - path: patches/argocd-server.yaml
