# values.yaml
metadata: {}

secrets:
  EXTERNAL_IP: ""

traefik:
  providers:
    # Enable traefik-owned CRDs since they are used for the main helm charts' configuration.
    kubernetesCRD:
      enabled: true
    # Enable Kubernetes Ingress API support.
    kubernetesIngress:
      enabled: true
    # Enable ingress-nginx compatibility
    kubernetesIngressNGINX:
      enabled: true

  # Enable a route to the dashboard for local proxy access.
  ingressRoute:
    dashboard:
      enabled: true

  ports:
    # Ensure that we never expose the dashboard with an ingress.
    traefik:
      expose:
        default: false
