{{- if .Values.secrets }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: traefik-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  template:
    type: Opaque
  encryptedData:
    {{- toYaml .Values.secrets | nindent 4 }}
{{- end }}
