metadata: {}

global:
  metadata:
    domain: local

immich:
  enabled: false
  controllers:
    main:
      containers:
        main:
          image:
            tag: v3.1.0
  server:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-server
              tag: v3.1.0@sha256:b434cb9287eea1471c9974845914d4dd328c9c2d652e446ed4930f99944f0ceb
  machine-learning:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/immich-app/immich-machine-learning
              tag: v3.1.0@sha256:5a0839dc5303cd7215bcd2180a26aed3af41675aefb3e75e5157e9f10ad16e6e

permissions:
  image:
    repository: busybox
    tag: 1.38.0@sha256:dc2d74b28e4cf8984fa52af1f39bc7c3d9c73760b41a74d629f5d11b1ab28616

postgres:
  image:
    repository: ghcr.io/immich-app/postgres
    tag: 14-vectorchord0.4.3-pgvectors0.2.0@sha256:bcf63357191b76a916ae5eb93464d65c07511da41e3bf7a8416db519b40b1c23
