apiVersion: v1
kind: Service
metadata:
  name: registry-headless
  labels:
    kubernetes.io/controller: registry
spec:
  type: ClusterIP
  selector:
    kubernetes.io/controller: registry
  clusterIP: None
  ports:
    - port: 5000
      targetPort: 5000
      name: http
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  labels:
    kubernetes.io/controller: registry
spec:
  type: ClusterIP
  selector:
    kubernetes.io/controller: registry
  ports:
    - port: 5000
      targetPort: 5000
      name: http
