apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-5"
spec:
  template:
    type: Opaque
  encryptedData:
    {{- range $_, $spec := .Values.configuration.secrets }}
    {{ $spec.name }}: {{ $spec.data }}
    {{- end }}
