{{- if .Values.secrets.CONTAINER_REGISTRY_CREDENTIALS }}
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: registry-credentials
spec:
  template:
    type: kubernetes.io/dockerconfigjson
    metadata:
      annotations:
        reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
        reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
  encryptedData:
    .dockerconfigjson: {{ .Values.secrets.CONTAINER_REGISTRY_CREDENTIALS }}
{{- end }}
