apiVersion: v1
kind: ConfigMap
metadata:
  name: registry-config
data:
  {{- range $_, $spec := .Values.configuration.files }}
  {{ $spec.name }}: |
    {{ tpl $spec.data $ | nindent 4}}
  {{ end -}}
