apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-styles-cm
data:
  theme.css: |
    .theme-light {
      --banner-background-color: #CAD9C3;
      --banner-color: #3C5130;
    }

    .theme-dark {
      --banner-background-color: #3C5130;
      --banner-color: #CAD9C3;
    }
